# Generated by Django 4.2.18 on 2025-04-15 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtwzProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dtwz_problem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DTWZProblemCompleted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('istrue', models.BooleanField(db_comment='是否正确')),
                ('collection', models.BooleanField(db_comment='是否收藏')),
                ('note', models.TextField(blank=True, db_comment='用户笔记', null=True)),
                ('problem', models.ForeignKey(db_comment='题目id', on_delete=django.db.models.deletion.CASCADE, to='datiApp.dtwzproblem')),
                ('user', models.ForeignKey(db_comment='用户id', on_delete=django.db.models.deletion.CASCADE, to='userApp.dtwzuser')),
            ],
            options={
                'db_table': 'dtwz_problem_completed',
                'managed': True,
                'indexes': [models.Index(fields=['user', 'problem'], name='user_problem')],
            },
        ),
    ]
