# Generated by Django 4.2.18 on 2025-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancompleted',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
