# Generated by Django 4.2.18 on 2025-05-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0002_alter_plancompleted_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plancompleted',
            table='planapp_plan_completed',
        ),
    ]
