# Generated by Django 4.2.18 on 2025-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp', '0003_alter_plancompleted_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancompleted',
            name='create_time',
            field=models.DateField(db_comment='创建时间'),
        ),
    ]
