# Generated by Django 4.2.18 on 2025-04-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='分类名称', max_length=64)),
            ],
            options={
                'db_table': 'readapp_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnglishArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_comment='标题', max_length=256)),
                ('cover', models.ImageField(db_comment='封面图片', upload_to='readApp/english_article')),
                ('content', models.TextField(db_comment='内容')),
                ('creator', models.CharField(db_comment='创建者', max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('watch_count', models.IntegerField(db_comment='观看次数', default=0)),
                ('star_count', models.IntegerField(db_comment='收藏次数', default=0)),
                ('category', models.ForeignKey(blank=True, db_comment='分类id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='readApp.category')),
            ],
            options={
                'db_table': 'readapp_english_article',
                'managed': True,
            },
        ),
    ]
