# Generated by Django 4.2.18 on 2025-04-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englisharticle',
            name='cover',
            field=models.ImageField(blank=True, db_comment='封面图片', null=True, upload_to='readApp/english_article'),
        ),
    ]
