# Generated by Django 4.2.18 on 2025-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readApp', '0002_alter_englisharticle_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englisharticle',
            name='content',
        ),
        migrations.AddField(
            model_name='englisharticle',
            name='chinese',
            field=models.TextField(db_comment='中文内容', null=True),
        ),
        migrations.AddField(
            model_name='englisharticle',
            name='english',
            field=models.TextField(db_comment='英文内容', null=True),
        ),
    ]
