# Generated by Django 4.2.18 on 2025-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readApp', '0003_remove_englisharticle_content_englisharticle_chinese_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englisharticle',
            name='chinese',
        ),
        migrations.RemoveField(
            model_name='englisharticle',
            name='english',
        ),
        migrations.AddField(
            model_name='englisharticle',
            name='content',
            field=models.TextField(db_comment='内容', null=True),
        ),
    ]
