# Generated by Django 4.2.18 on 2025-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtwzUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='用户名', max_length=32)),
                ('password', models.CharField(db_comment='用户密码', max_length=32)),
                ('email', models.CharField(db_comment='用户邮箱', max_length=32)),
                ('phone', models.CharField(db_comment='用户手机号', max_length=32)),
                ('avatar', models.ImageField(blank=True, db_comment='用户头像', null=True, upload_to='avatar')),
            ],
            options={
                'db_table': 'dtwz_user',
                'db_table_comment': '用户管理表',
                'managed': True,
            },
        ),
    ]
