# Generated by Django 4.2.18 on 2025-04-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtwzuser',
            name='avatar',
            field=models.ImageField(blank=True, db_comment='用户头像', null=True, upload_to='userAPP/avatar'),
        ),
    ]
